"""empty message

Revision ID: 802c1502f660
Revises: 1a59c35ce531
Create Date: 2024-03-27 17:48:32.244196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802c1502f660'
down_revision = '1a59c35ce531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
